version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - pip install -r requirements.txt
      - python app.py & sleep 5
      - echo "Build successful"
