version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo Build started
      - docker build -t python-app .
      - echo Build completed

artifacts:
  files:
    - '**/*'
